services:
  mariadb-oldest-v7:
    container_name: sequelize-mariadb-oldest-v7
    image: mariadb:10.4.30
    environment:
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
      MYSQL_ROOT_PASSWORD: sequelize_test
    ports:
      - 21103:3306
    volumes:
      - mariadb-oldest-v7:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "-usequelize_test", "-psequelize_test", "status"]
      interval: 3s
      timeout: 1s
      retries: 10

networks:
  default:
    name: sequelize-mariadb-oldest-v7-network

volumes:
  mariadb-oldest-v7:
    name: sequelize-mariadb-oldest-v7-volume
